"""Add RecommendationCheck model

Revision ID: ec0251243212
Revises: 5d8c5f8a54df
Create Date: 2025-05-19 13:09:48.341763

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec0251243212'
down_revision = '5d8c5f8a54df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('recommendation_tracking')
    op.drop_table('recommendation_ratios')
    
    op.create_table('recommendation_checks',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('date', sa.Date(), nullable=False),
        sa.Column('state', sa.String(length=50), nullable=False),
        sa.Column('recommendation_id', sa.Integer(), nullable=False),
        sa.Column('was_taken', sa.Boolean(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['recommendation_id'], ['recommendations.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('recommendation_checks')
    
    op.create_table('recommendation_ratios',
        sa.Column('id', sa.INTEGER(), nullable=False),
        sa.Column('state', sa.VARCHAR(length=2), nullable=False),
        sa.Column('date', sa.DATE(), nullable=False),
        sa.Column('ratio', sa.FLOAT(), nullable=False),
        sa.Column('created_at', sa.DATETIME(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recommendation_tracking',
        sa.Column('id', sa.INTEGER(), nullable=False),
        sa.Column('state', sa.VARCHAR(length=2), nullable=False),
        sa.Column('date', sa.DATE(), nullable=False),
        sa.Column('implemented_date', sa.DATE(), nullable=True),
        sa.Column('recommendation_type', sa.VARCHAR(length=50), nullable=False),
        sa.Column('recommendation_value', sa.VARCHAR(length=255), nullable=False),
        sa.Column('was_implemented', sa.BOOLEAN(), nullable=True),
        sa.Column('created_at', sa.DATETIME(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
